import * as fs from 'fs';
import * as path from 'path';

/**
 * Global setup for Playwright E2E tests.
 * Runs ONCE before all workers start, ensuring proper directory initialization.
 */
async function globalSetup() {
  const reportDir = path.join(
    process.cwd(),
    '..',
    '..',
    'accessibility-reports',
  );

  // Clear and recreate the reports directory once before all tests
  if (fs.existsSync(reportDir)) {
    // Remove all existing report files (but keep the directory)
    const files = fs.readdirSync(reportDir);
    for (const file of files) {
      fs.unlinkSync(path.join(reportDir, file));
    }
    console.log(`Cleared accessibility-reports directory: ${reportDir}`);
  } else {
    fs.mkdirSync(reportDir, { recursive: true });
    console.log(`Created accessibility-reports directory: ${reportDir}`);
  }

  // Create README to ensure directory is never empty (for artifact upload)
  const readmePath = path.join(reportDir, 'README.md');
  fs.writeFileSync(
    readmePath,
    '# Accessibility Reports\n\n' +
      'This directory contains accessibility test reports generated by Playwright.\n\n' +
      'Reports are organized by browser/device and test suite:\n' +
      '- `accessibility-report-{browser}-{suite}.md`\n\n' +
      'If README.md is the only file here, no accessibility violations were found!\n',
    'utf-8',
  );

  console.log('Global setup complete for accessibility tests');
}

export default globalSetup;
